version: '3.8'

services:
  ib-gateway:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ib-gateway-service
    ports:
      - "5050:5050"  # IB Gateway Service API
      - "5001:5000"  # Client Portal Gateway
    environment:
      # Service configuration
      - IB_GATEWAY_SERVICE_PORT=5050
      - IB_GATEWAY_DATA_STORE_PATH=/data

      # Authentication settings
      - IB_AUTH_MAX_ATTEMPTS=4
    volumes:
      - ib-gateway-data:/data
    networks:
      - docker_options-trader-network
    restart: unless-stopped
    # Health check to verify service is running
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/api/service"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  ib-gateway-data:
    driver: local

networks:
  docker_options-trader-network:
    external: true
